
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SensorMonitoringSystem
{

using System;
    using System.Collections.Generic;
    
public partial class Companies_AuditEntity
{

    public int AuditCompanyID { get; set; }

    public int CompanyID { get; set; }

    public string CompanyName { get; set; }

    public Nullable<int> OldCompanyID { get; set; }

    public string OldCompanyName { get; set; }

    public string ActionFrom { get; set; }

    public Nullable<System.DateTime> ActionDate { get; set; }

    public string ActionType { get; set; }

}

}
