
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SensorMonitoringSystem
{

using System;
    using System.Collections.Generic;
    
public partial class DirtyWordsEntity
{

    public int DirtyWordID { get; set; }

    public string DirtyWord { get; set; }

}

}
