
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SensorMonitoringSystem
{

using System;
    using System.Collections.Generic;
    
public partial class SensorsEntity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SensorsEntity()
    {

        this.SensorsDatas = new HashSet<SensorsDatasEntity>();

    }


    public int SensorID { get; set; }

    public int CompanyID { get; set; }

    public string SensorDescription { get; set; }

    public string SensorAddress { get; set; }

    public int GraphicalMinValue { get; set; }

    public int GraphicalMaxValue { get; set; }

    public decimal LowestCriticalValue { get; set; }

    public decimal HighestCriticalValue { get; set; }

    public string SensorUnit { get; set; }

    public bool IsSpecificSensor { get; set; }



    public virtual CompaniesEntity Companies { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SensorsDatasEntity> SensorsDatas { get; set; }

}

}
