
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SensorMonitoringSystem
{

using System;
    using System.Collections.Generic;
    
public partial class SensorsDatasEntity
{

    public int DataID { get; set; }

    public int SensorID { get; set; }

    public decimal ReadValue { get; set; }

    public System.DateTime ReadValueTime { get; set; }



    public virtual SensorsEntity Sensors { get; set; }

}

}
