
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SensorMonitoringSystem
{

using System;
    using System.Collections.Generic;
    
public partial class Sensors_AuditEntity
{

    public int AuditSensorID { get; set; }

    public int SensorID { get; set; }

    public int CompanyID { get; set; }

    public string SensorDescription { get; set; }

    public string SensorAddress { get; set; }

    public int GraphicalMinValue { get; set; }

    public int GraphicalMaxValue { get; set; }

    public decimal LowestCriticalValue { get; set; }

    public decimal HighestCriticalValue { get; set; }

    public string SensorUnit { get; set; }

    public bool IsSpecificSensor { get; set; }

    public Nullable<int> OldAuditSensorID { get; set; }

    public Nullable<int> OldCompanyID { get; set; }

    public string OldSensorDescription { get; set; }

    public string OldSensorAddress { get; set; }

    public Nullable<int> OldGraphicalMinValue { get; set; }

    public Nullable<int> OldGraphicalMaxValue { get; set; }

    public Nullable<decimal> OldLowestCriticalValue { get; set; }

    public Nullable<decimal> OldHighestCriticalValue { get; set; }

    public string OldSensorUnit { get; set; }

    public Nullable<bool> OldIsSpecificSensor { get; set; }

    public string ActionFrom { get; set; }

    public Nullable<System.DateTime> ActionDate { get; set; }

    public string ActionType { get; set; }

}

}
