
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SensorMonitoringSystem
{

using System;
    using System.Collections.Generic;
    
public partial class Users_AuditEntity
{

    public int AuditUserID { get; set; }

    public int UserID { get; set; }

    public int CompanyID { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Username { get; set; }

    public byte[] Password { get; set; }

    public string PasswordKey { get; set; }

    public bool IsActivated { get; set; }

    public bool IsApproved { get; set; }

    public long RegistrationCode { get; set; }

    public string UserType { get; set; }

    public Nullable<int> OldUserID { get; set; }

    public Nullable<int> OldCompanyID { get; set; }

    public string OldName { get; set; }

    public string OldSurname { get; set; }

    public string OldUsername { get; set; }

    public byte[] OldPassword { get; set; }

    public string OldPasswordKey { get; set; }

    public Nullable<bool> OldIsActivated { get; set; }

    public Nullable<bool> OldIsApproved { get; set; }

    public Nullable<long> OldRegistrationCode { get; set; }

    public string OldUserType { get; set; }

    public string ActionFrom { get; set; }

    public Nullable<System.DateTime> ActionDate { get; set; }

    public string ActionType { get; set; }

}

}
