
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SensorMonitoringSystem
{

using System;
    using System.Collections.Generic;
    
public partial class UsersDetails_AuditEntity
{

    public int AuditDetailID { get; set; }

    public int DetailID { get; set; }

    public int UserID { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string Adress { get; set; }

    public System.DateTime DateOfBirth { get; set; }

    public Nullable<int> OldDetailID { get; set; }

    public Nullable<int> OldUserID { get; set; }

    public string OldPhoneNumber { get; set; }

    public string OldEmail { get; set; }

    public string OldCountry { get; set; }

    public string OldCity { get; set; }

    public string OldDistrict { get; set; }

    public string OldAdress { get; set; }

    public Nullable<System.DateTime> OldDateOfBirth { get; set; }

    public string ActionFrom { get; set; }

    public Nullable<System.DateTime> ActionDate { get; set; }

    public string ActionType { get; set; }

}

}
