
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SensorMonitoringSystem
{

using System;
    using System.Collections.Generic;
    
public partial class UsersDetailsEntity
{

    public int DetailID { get; set; }

    public int UserID { get; set; }

    public string City { get; set; }

    public System.DateTime DateOfBirth { get; set; }

    public string Email { get; set; }

    public string Country { get; set; }

    public string PhoneNumber { get; set; }

    public string District { get; set; }

    public string Address { get; set; }



    public virtual UsersEntity Users { get; set; }

}

}
